### ISSUE TITLE
A variant without blue color scheme

### ISSUE THREAD

**Issue by FcoMarcosMAbreu** [daltonmenezes/aura-theme#1]
Tem como fazer uma variante que não tenha nada de azul ou próximo dele? A luz azul é um dos vilões da melatonina. Eu gosto de variações entre amarelo, laranja e vermelho combinado com preto.

**Comment by daltonmenezes** [comment]
@FcoMarcosMAbreu Do you mean about the UI colors or syntax highlighting also?
