### ISSUE TITLE
VS Code Integrated terminal colors don't match external terminal themes

### ISSUE THREAD

**Issue by redoxeon** [daltonmenezes/aura-theme#102]
The terminal colors for the VS Code theme don't match what is available for the terminal theme.

Can these colors be added/fixed?
[Integrated terminal colors documentation](https://code.visualstudio.com/api/references/theme-color#integrated-terminal-colors)

Correct (Alacritty)
![alacritty](https://user-images.githubusercontent.com/10731372/154143996-5db8e00e-548d-4d20-9f66-81586cfb607a.png)

Incorrect (VS Code Integrated Terminal)
![vs-code](https://user-images.githubusercontent.com/10731372/154144032-1ec525f5-b27e-47c0-83d8-65cf98e723dc.png)

**Comment by daltonmenezes** [comment]
Hi @redoxeon , since we can have more than one external terminal and different people can use different terminals and these terminals as ports will probably never go without differences, it will be troublesome to try to combine a specific one, for now I believe keeping vscode as it is better. 💜
