### ISSUE TITLE
Theme for Mattermost

### ISSUE THREAD

**Issue by luisstd** [daltonmenezes/aura-theme#139]
I think an implementation of the Aura theme for [Mattermost](https://mattermost.com/) would be great. The theming seems to work similarly to Slack and maybe some parts of the already existing Slack port could be used. There is [documentation](https://docs.mattermost.com/welcome/customize-your-theme.html) on the Mattermost website on how to create a custom theme and how to import a theme from Slack.

**Comment by mahendradambe** [comment]
Hey, I've created a [Mattermost Port](https://github.com/mahendradambe/aura-theme/tree/feat/mattermost) using Aura Dark.
You can check it out [here](https://raw.githubusercontent.com/mahendradambe/aura-theme/feat/mattermost/packages/mattermost/aura-dark.json).


@daltonmenezes - Can I go ahead with a PR?

**Comment by daltonmenezes** [comment]
@mahendradambe sure, thank you so much 💜
