### ISSUE TITLE
Theme for WebStorm

### ISSUE THREAD

**Issue by mp-alexchadwick** [daltonmenezes/aura-theme#140]
I quite like how the aura-theme looks, but my favourite editor is WebStorm, could we have a port for Intellij products? Resources: https://www.jetbrains.com/help/webstorm/user-interface-themes.html https://www.jetbrains.com/help/webstorm/settings-colors-and-fonts.html

**Comment by woosal1337** [comment]
Agreed. I am also using JetBrains products and would love to see the theme among.

**Comment by delucca** [comment]
+1

**Comment by tobiashoeft** [comment]
+1

**Comment by daltonmenezes** [comment]
Hi @mp-alexchadwick , there's already a [discussion about JetBrains IDE family](https://github.com/daltonmenezes/aura-theme/discussions/127), but we need help to make this happen. Unfortunately, I can't do this by myself right now. For this reason, I'm closing this issue, when someone flags the interest to make the port there, I'll convert that discussion to an issue. Thanks 💜
