### ISSUE TITLE
Theme for PyCharm

### ISSUE THREAD

**Issue by FranciscoRVW** [daltonmenezes/aura-theme#144]
It would be very nice to have this theme on the jetbrains IDE family

**Comment by daltonmenezes** [comment]
Hi @FranciscoRVW , there's already [discussion about JetBrains IDE family](https://github.com/daltonmenezes/aura-theme/discussions/127), but we need help to make this happen. Unfortunately, I can't do this by myself right now. For this reason, I'm closing this issue, when someone flags the interest to make the port there, I'll convert that discussion to an issue. Thanks 💜
