### ISSUE TITLE
CLI providing error when making port

### ISSUE THREAD

**Issue by DanKlaver15** [daltonmenezes/aura-theme#146]
Receiving an error when using the make port command with the CLI.  Error is [ERR_REQUIRE_ESM]: require() not supported.  More verbose error message in the terminal shows it’s the cpy module.  I was able to get it working by downgrading cpy to version 8.1.2 which was the last version built using CommonJS instead of ESM.

**Comment by DanKlaver15** [comment]
Additional errors found when attempting to publish a port
![CleanShot 2022-04-14 at 09 36 07](https://user-images.githubusercontent.com/9391497/163413357-f02e8c5d-2dba-4353-a63a-2ba32be8c191.png)
:

**Comment by daltonmenezes** [comment]
Hi @DanKlaver15 , I just tried it now and everything is working as expected. Here are the version I'm running it on:

```
yarn v1.22.18
node v16.13.1
```
Can you try it please using these versions?

**Comment by DanKlaver15** [comment]
@daltonmenezes I updated yarn and I think that did the trick since I was able to publish the PR for the Nova port earlier today.

**Comment by daltonmenezes** [comment]
@DanKlaver15 All right, I'm closing this issue for now, please let me know if you face any issues, thanks.
