### ISSUE TITLE
[Chrome | Windows] window control buttons looks weird

### ISSUE THREAD

**Issue by Araxeus** [daltonmenezes/aura-theme#149]
![image](https://user-images.githubusercontent.com/78568641/164051459-18a3e15f-f4dc-47b8-825c-565248183331.png)

I'm not sure if this is intended?

IMO They should have the same color as the background of the titlebar, like pretty much all other themes

I would love to use this theme but those buttons are really ugly right now 😅

**Comment by daltonmenezes** [comment]
Hi @Araxeus , could you please update to [v1.0.2](https://chrome.google.com/webstore/detail/aura-theme/ddipnaombfnagpagnpdkdinoekfhfjoh) to check if this issue was properly fixed?

**Comment by Araxeus** [comment]
It is properly fixed, thanks alot

I'm now a proud user of aura theme on chrome 😉

**Comment by daltonmenezes** [comment]
@Araxeus Thanks for the feedback 💜
