### ISSUE TITLE
Theme for Vim

### ISSUE THREAD

**Issue by elloello** [daltonmenezes/aura-theme#150]
i'm aware there's a theme for neovim. but it'd would be great to have a vim theme too.

**Comment by daltonmenezes** [comment]
Hi @elloello there is already a request for this port. [Take a look at this discussion](https://github.com/daltonmenezes/aura-theme/discussions/117), please. For this reason, I'm closing this issue.

**Comment by elloello** [comment]
ah thanks. didn't look at discussions haha
