### ISSUE TITLE
accent20 has wrong HEX code

### ISSUE THREAD

**Issue by ssebastianoo** [daltonmenezes/aura-theme#157]
It currently is `#3d375e7f` but it should be `#3d375e`.

Those two final characters are making the color becoming gray.

https://github.com/daltonmenezes/aura-theme/blob/main/packages/color-palettes/README.md?plain=1#L70=

**Comment by ssebastianoo** [comment]
## `background-color: #3d375e7f`
![image](https://user-images.githubusercontent.com/48064277/175354363-b68f54c3-bd0f-4ef9-9816-ebdd9270911a.png)
## `background-color: #3d375e`
![image](https://user-images.githubusercontent.com/48064277/175354451-042c7fa6-9fef-4077-a884-1a5e835ed827.png)

**Comment by daltonmenezes** [comment]
Hi @ssebastianoo , accent20 is right, it's a hex with opacity as you can notice in the following image from Chrome, and it should be used in text selections for example. Hex with opacity is not supported by all apps in that case you can try the RGBA version: 61,55,94,0.5

![Captura de Tela 2022-06-23 às 16 08 14](https://user-images.githubusercontent.com/1149845/175378753-e1d6a0f8-fda0-4b20-9b6a-d3b44136863e.png)

**Comment by ssebastianoo** [comment]
Oh ok thanks, sorry
