### ISSUE TITLE
Port for Gnome Terminal

### ISSUE THREAD

**Issue by Cristuker** [daltonmenezes/aura-theme#16]
I like to use oh my zsh and i suggest to create a color scheme to him

**Comment by daltonmenezes** [comment]
Hi @Cristuker , I'm using Aura with oh my zsh on Hyper and iTerm and it works as expected, what terminal are you using?

**Comment by Cristuker** [comment]
I use gnome terminal, have a way to install ? Because just have by hyper command

**Comment by daltonmenezes** [comment]
@Cristuker I'll take a look at this for sure at some moment, I can't do this right now but I'll.

**Comment by Cristuker** [comment]
No problem. Thanks <3
