### ISSUE TITLE
Termux port

### ISSUE THREAD

**Issue by holiq** [daltonmenezes/aura-theme#161]
Hello, I tried to apply the aura theme to termux and I think the results are good, so can i make a pr for the termux port?
Here are the results of applying the aura theme on termux
![Screenshot_20220810-205705_Termux-picsay](https://user-images.githubusercontent.com/30729921/184006286-69206e81-0c93-48a4-8c52-873fb33a3a3d.png)

**Comment by daltonmenezes** [comment]
Hi @holiq , You can work on this for sure, but don't forget to read the [docs](https://github.com/daltonmenezes/aura-theme#documentation) to submit the PR properly!

Thanks 💜
