### ISSUE TITLE
[Chrome Theme] Folder name on bookmark bar has a weird color

### ISSUE THREAD

**Issue by Araxeus** [daltonmenezes/aura-theme#167]
![image](https://user-images.githubusercontent.com/78568641/187958365-94f8d9f3-ecb9-43c2-bc1d-87d47cb3cfa9.png)

The folder name seems greyed out, which is kinda weird

Here's how it looks usually:

![image](https://user-images.githubusercontent.com/78568641/187958681-3e0d987d-4a6b-4d69-abd5-5cde8865a408.png)

**Comment by daltonmenezes** [comment]
Hi @Araxeus , this is Chrome or another browser like Edge?

**Comment by Araxeus** [comment]
same as #166. after restarting my pc it seems to be fixed and back to normal color, not sure what caused this

(chrome , win10 )
