### ISSUE TITLE
Aura theme for JetBrains products

### ISSUE THREAD

**Issue by reoccurcat** [daltonmenezes/aura-theme#169]
This is just an idea, but is it possible to get this theme developed for any JetBrains products? I main these IDEs when I program, and I would love to have this theme on them, but there doesn't seem to be an Aura for them yet. Any chance this could be done? You'd have my gratitude lol

**Comment by daltonmenezes** [comment]
Hi @reoccurcat , there's already a [discussion about JetBrains IDE family](https://github.com/daltonmenezes/aura-theme/discussions/127), but we need help to make this happen. Unfortunately, I can't do this by myself right now. For this reason, I'm closing this issue. Thanks 💜
