### ISSUE TITLE
Is there interest in a Waybar port?

### ISSUE THREAD

**Issue by Hendrikto** [daltonmenezes/aura-theme#178]
Hi Dalton,

I created a Waybar configuration with the Aura Theme. At a quick glance, it looks like this:

![image](https://user-images.githubusercontent.com/8006842/223426773-5dbe62fc-794f-4034-8a60-cfaac0317347.png)

Would you be interested in taking this on as an official port? In that case I could prepare a PR, and we could discuss the details.

Best,
Hendrik

**Comment by daltonmenezes** [comment]
Hi @Hendrikto , sure. Thanks for that, I'll be waiting for the PR 💜

**Comment by Hendrikto** [comment]
I sent PR #179, but there are some open questions.
