### ISSUE TITLE
Sway port

### ISSUE THREAD

**Issue by Hendrikto** [daltonmenezes/aura-theme#180]
I created an Aura Theme color scheme for sway:

* `focused` (floating), `focused_inactive` (left), `unfocused` (right):

  ![image](https://user-images.githubusercontent.com/8006842/223750636-19aee8ed-f70b-4050-a0db-56f1e2a47ef3.png)

* `urgent`:

  ![image](https://user-images.githubusercontent.com/8006842/223749774-2aa85505-3f92-4d85-addc-a2b572fd28a3.png)

* indicator ("The color used to indicate where a new view will open."):

  ![image](https://user-images.githubusercontent.com/8006842/223751771-c09ac577-f367-4c4c-8c17-d7059db3f63d.png)

It goes well with the [Waybar port](https://github.com/daltonmenezes/aura-theme/pull/179), and is depicted as such in the screenshots.

If you are interested, I could prepare a PR for this port.

**Comment by daltonmenezes** [comment]
@Hendrikto sure, please 💜

**Comment by Hendrikto** [comment]
It's pretty late where I live, I will get to it tomorrow :)

**Comment by Hendrikto** [comment]
Preliminary preview:

![image](https://user-images.githubusercontent.com/8006842/224580576-bdbe9de3-4975-40f1-8fb0-2cf72690b917.png)
