### ISSUE TITLE
fix: grammatical improvement

### ISSUE THREAD

**Issue by Hendrikto** [daltonmenezes/aura-theme#185]
Hi Dalton,

I noticed a small grammatical error in the README template for ports. It says

> A beautiful dark theme for {{ portName }} and **another** apps

"Another" implies a single other app, i.e. "and one other app". It should be "other" instead.

This affects 4 files:

```bash
~/projects/aura-theme ❯ git grep -l 'and another' src/                                                                                                                                    [main]
src/ports/chrome/templates/README.md
src/ports/firefox/templates/README.md
src/shared/templates/readmes/basic-heading.md
src/shared/templates/readmes/npm-heading.md
```

I already started working on [a fix](https://github.com/Hendrikto/aura-theme/tree/fix/grammar). I think we should replace the custom headings in the Firefox and Chrome ports with basic-heading, instead of manually fixing the mistake. That should set us up better for future changes. Then we would need to rebuild all ports, for the fix to take effect.

If you agree, I can go ahead with the fix, and send a PR.

**Comment by daltonmenezes** [comment]
@Hendrikto the grammar fix is welcome, but replacing the custom headers in the mentioned browsers ports with basic-heading is a problem because the version you are talking about is related to their respective versions on store, those versions are not hard-coded in their readme templates!

**Comment by Hendrikto** [comment]
Okay, understood :+1:
