### ISSUE TITLE
[Gnome Terminal] Cursor is purple instyead of white

### ISSUE THREAD

**Issue by bmarcot** [daltonmenezes/aura-theme#194]
![image](https://github.com/daltonmenezes/aura-theme/assets/1838157/8f7ae9d3-2cc3-404c-8122-1311d0018ee7)

I think cursor should be white to match other terminals. How can I turn it white instead of purple?

Thanks

**Comment by daltonmenezes** [comment]
@bmarcot you can just change the color in your `aura-theme.dconf` local file as you like

https://github.com/daltonmenezes/aura-theme/blob/main/packages/gnome-terminal/aura-theme.dconf#L6
