### ISSUE TITLE
Issue with Flash of White on restoring history tabs or Window Open in Chrome

### ISSUE THREAD

**Issue by Freddd13** [daltonmenezes/aura-theme#203]
**Description:**
I am experiencing an issue with Chrome when using the theme. Every time I either reopen a closed tab using the Ctrl + Shift + T shortcut or open a new window, there is a brief but noticeable flash of white before the dark theme is applied. This sudden flash of bright light is particularly jarring and uncomfortable, especially in a low-light environment.
chrome version: 119.0.6045.124

**Steps to Reproduce:**
Apply the theme to Chrome.
Close a tab or window.
Reopen the tab using Ctrl + Shift + T or open a new window.

**Expected Behavior:**
The new tab or window should open with the dark theme applied immediately, without any prior flash of white.

**Actual Behavior:**
There is a flash of white on opening a new tab or window before the theme loads, causing a discomforting glare.

I don't know whether it is a theme-related issue or a browser-related issue, but it would be greatly appreciated if this could be looked into. 
Thank you for your attention to this matter.

**Comment by daltonmenezes** [comment]
@Freddd13 This does not happen here, it is probably something related to the version of Chrome you are using, a disabled hardware acceleration case or if you are using Linux, it could be something with Chrome itself.
