### ISSUE TITLE
Error while installing plugin in Insomnia

### ISSUE THREAD

**Issue by jonathafernandes** [daltonmenezes/aura-theme#215]
Failed to install insomnia-plugin-aura-theme

There may be an issue with the plugin itself, as a note you can discover and install plugins from the [Plugin Hub.](https://insomnia.rest/plugins)
Additional Information
Error: Error invoking remote method 'installPlugin': Error: Yarn error /snap/insomnia/255/insomnia: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

    at IpcRenderer.invoke (node:electron/js2c/renderer_init:2:6995)
    at async onSubmit (file:///snap/insomnia/255/resources/app.asar/mainWindow-zajGd_wC.js:1493:513)

**Comment by daltonmenezes** [comment]
Hi @jonathafernandes this is not related to aura-theme plugin itself, please check the following insomnia issue https://github.com/Kong/insomnia/issues/4316
