### ISSUE TITLE
Recommended configuration

### ISSUE THREAD

**Issue by fariasmateuss** [daltonmenezes/aura-theme#22]
Hey, @daltonmenezes !

First congratulations on the project

I have a suggestion

https://github.com/daltonmenezes/aura-theme/blob/68c2e628b82b58791ca86b3e20519264d57d003a/.eslintrc#L17

Isn't it missing to extend the prettier rule in your .eslintrc file?

```json
"rules": {
     "prettier / prettier": "error"
   }
``` 
According to the eslint-plugin-prettier plugin documentation.

**Comment by daltonmenezes** [comment]
@fariasmateuss Thanks bro.

About your question, the following conf do the job:
`"extends": ["plugin:prettier/recommended"]`

As the official docs says about the **plugin:prettier/recommended** :
```
Enables eslint-plugin-prettier.
Sets the prettier/prettier rule to "error".
Extends the eslint-config-prettier configuration.
```
