### ISSUE TITLE
VSCode: Make scrollbar color alpha

### ISSUE THREAD

**Issue by jvzaniolo** [daltonmenezes/aura-theme#35]
The scrollbar color on VSCode doesn't have an alpha and it's hiding some useful information.

New or modified lines are shown in the scrollbar with colors green or blue but the actual scrollbar is all black so I can't see the colors underneath it.

![image](https://user-images.githubusercontent.com/54036572/135692449-0493d8c5-cb3b-434c-ab71-7d4a06cc003f.png)

The black gap in this screenshot is the scrollbar overlapping the green and blue colors

**Comment by daltonmenezes** [comment]
Hi @jvzaniolo , how about this one? 🤔
![Kapture 2021-10-01 at 19 47 10](https://user-images.githubusercontent.com/1149845/135693679-7c272fdd-9b3e-4022-b0a9-3832ccaf4c3e.gif)

**Comment by jvzaniolo** [comment]
Now I can't even see the scrollbar 😂 Could you make it a little more solid?

**Comment by daltonmenezes** [comment]
@jvzaniolo  hehe, I think this one should be good, it's the same accent for text selection.
![Kapture 2021-10-01 at 20 04 43](https://user-images.githubusercontent.com/1149845/135694575-bb3f78bf-9b39-4d01-a892-ac72618aafde.gif)

**Comment by jvzaniolo** [comment]
@daltonmenezes This is perfect, thank you!
