### ISSUE TITLE
VSCode: Spaceship git colors are the same as the directory

### ISSUE THREAD

**Issue by jvzaniolo** [daltonmenezes/aura-theme#37]
# Summary

I'm a spaceship theme user and the git colors on VSCode are a little off from the ones in the Terminal.app and it's getting a little confusing to read.

# Screenshots

![Terminal colors on VSCode](https://user-images.githubusercontent.com/54036572/135780642-a633c204-13f0-4b88-b695-5aa79c2a0b57.png)

![Terminal colors in Terminal.app](https://user-images.githubusercontent.com/54036572/135780721-1b355d2a-ab91-4556-815a-19af8a217507.png)

**Comment by daltonmenezes** [comment]
Hello @jvzaniolo , as this seems to be happening only with the spaceship theme on vscode, I'm afraid if we change the color by default it might cause problems for others. It should probably be better to apply the color change manually for now.

You can open the settings.json in your vscode and add it to it:
```json
"workbench.colorCustomizations": {
  "terminal.ansiBrightMagenta": "#a277ff"
}
```
I'm closing this issue for now, but feel free to reopen it if you feel the need.
