### ISSUE TITLE
Permission to make a port for Warp terminal

### ISSUE THREAD

**Issue by chris-c-thomas** [daltonmenezes/aura-theme#46]
I'd like to port Aura theme to the newish Warp terminal. It can be found at https://www.warp.dev

Should be straight forward. You do need to request access to the app since it's still in beta but it's a really great terminal that I'm enjoying so far (my main terminal is Hyper).

@daltonmenezes if it's okay with you I'd like to go forward with it. 

Thanks.

**Comment by chris-c-thomas** [comment]
I should point out that after requesting access, you can join their Discord, and I think that instantly gives you access. At least, it did for me.

**Comment by daltonmenezes** [comment]
Hi @chris-c-thomas , are you still working on this port?
