### ISSUE TITLE
Telegram select from file does not accept .theme

### ISSUE THREAD

**Issue by shoaib30** [daltonmenezes/aura-theme#49]
As per the instruction

> 1. Download the theme.tdesktop-theme file
> 2. In Telegram Desktop, go to Settings -> Chat Settings -> and under the Chat background section click on Choose from file.
> 3. Select the theme.tdesktop-theme file you downloaded.
> 4. Click Keep Changes to apply the theme.

Running Telegram Desktop (8.1.3 (222037) AppStore)  on OSX (11.6)

Chat background is available under _Settings -> Appearance -> Chat Background_

On choosing _Select From File_, only image files are enabled all other files are disabled from selection

**Comment by daltonmenezes** [comment]
Hi @shoaib30 Telegram Desktop on AppStore is not the latest version available, try it from the [official website](https://telegram.org/dl/desktop/mac)
