### ISSUE TITLE
Port for Vim

### ISSUE THREAD

**Issue by shivesh01** [daltonmenezes/aura-theme#56]
I think there is a need for vim plugin because vim is popular nowadays..

**Comment by ashishbinu** [comment]
I would like to work on this issue.

**Comment by patrickdeangelis** [comment]
@ashishbinu how can I help the development?

**Comment by kavinvalli** [comment]
How long will this and #28 take @ashishbinu? Looking forward to the port

**Comment by Arjun31415** [comment]
I have created a port, however it is still lacking as I am not very familiar with themeing in vim
