### ISSUE TITLE
Unable to find theme in VS Code's Extension Marketplace

### ISSUE THREAD

**Issue by squigjess** [daltonmenezes/aura-theme#57]
Searching for `aura theme`, `aura`, `ext install DaltonMenezes.aura-theme`, `DaltonMenezes.aura-theme`, `aura-theme`, and `DaltonMenezes` refuses to bring up the Aura theme. Instead, what gets returned is either nothing at all, or the below list of themes, in which Aura cannot be seen.

![Screenshot of what appears when "aura theme" is searched in the Extensions Marketplace](https://imgur.com/7W1jXC4.png)

**Comment by daltonmenezes** [comment]
Hi @squigjess , is that the real Visual Studio Code or something like Gitpod? Can you provide me more details, please?

**Comment by squigjess** [comment]
Hi Dalton. This is on Manjaro Linux. I installed it using the `code` package provided by Arch Linux's package manager.

**Comment by squigjess** [comment]
Currently I am using version 1.61.0-1

**Comment by daltonmenezes** [comment]
@squigjess I'm closing this issue for now, but feel free to reopen it if you feel the need.
