### ISSUE TITLE
Aura-theme Windows installation problem 

### ISSUE THREAD

**Issue by Grezor** [daltonmenezes/aura-theme#66]
I've been trying to install the aura theme on insomnia to see what it looks like. It's a very nice theme by the way! 

**I have encountered a problem on windows 10.**
![image](https://user-images.githubusercontent.com/38507456/138160391-b1dcbab5-0413-4414-a25e-1d3d9d584809.png)

If you want to install the theme : 
- Clone the 3 files (logo.png, package.json, and the index.js) found [here](https://github.com/daltonmenezes/aura-theme/tree/main/packages/insomnia)
- create a folder in the insomnia plugins directory with the name: insomnia-plugin-aura-theme
- Then move all the cloned files in the Roaming\Insomnia\plugins\insomnia-plugin-aura-theme
- Then go to : Preferences -> themes -> theme name : Aura-theme

![image](https://user-images.githubusercontent.com/38507456/138159951-cfc9fcbd-9c41-440a-b4ff-6180ec4d66f9.png)

**I would like to know if other people have the same concern?**

**Comment by Grezor** [comment]
I add the error during the installation
![image](https://user-images.githubusercontent.com/38507456/138283302-8c5d324e-3c5b-4154-bbb0-2b74e4fca6a9.png)

**Comment by karesztrk** [comment]
As a workaround, you can install it manually. I had the same problem as you before.

**Comment by daltonmenezes** [comment]
Hi @Grezor , I think this is not an issue with the Aura theme itself, but with Insomnia on Windows. Try to open an issue in the [official Insomnia repository](https://github.com/Kong/insomnia) reporting this behavior, please, so for this reason I'll close this issue for now, ok?

**Comment by Grezor** [comment]
@daltonmenezes  No worries, and I suspected that the concern was from insomnia, but I wanted confirmation
