### ISSUE TITLE
Can't select text in Debug Console

### ISSUE THREAD

**Issue by joarobles** [daltonmenezes/aura-theme#75]
Hi there!
I can't select text from the Debug Console using Aura (in any of its variants),
Mouse selection or Cmd+A won't work, this is my configuration:

Aura Theme v2.1.0

**VS Code**
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:49:28.381Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by daltonmenezes** [comment]
Hi @joarobles , I don't know, but this doesn't seem like an issue with Aura Theme or any theme in general. Does this not happen on another ones?
