### ISSUE TITLE
Theme on Microsoft Edge is broken

### ISSUE THREAD

**Issue by max-programming** [daltonmenezes/aura-theme#80]
Just discovered this great theme! But on Microsoft Edge, it does not look good as on Chrome.
![image](https://user-images.githubusercontent.com/51731966/142027676-53733617-5f3a-4447-b8a6-80cb2c3b42f6.png)

**Comment by daltonmenezes** [comment]
Thanks @max-programming , but there's no port for Edge yet, if we change the things on Chrome in favor of Edge, Chrome will be broken, for this reason I'm closing this issue, but you can open a new one requesting an Edge port. 💜

**Comment by max-programming** [comment]
@daltonmenezes I think you should publish the same theme with the changes made to the [Edge Add-ons Store](https://microsoftedge.microsoft.com/addons/microsoft-edge-themes?form=MT001Y)

**Comment by daltonmenezes** [comment]
@max-programming This is a good idea, but I can't do it right now without checking the Edge add-ons docs to see the things I'll change to adapt to Edge and its store. And there is the possibility that it will never look like Chrome, after all it is another browser despite having the same base. Creating the issue requesting for the port makes the port traceable and opens the possibility for it to be developed by whoever wants to do so without waiting for my availability.

**Comment by daltonmenezes** [comment]
Hi @max-programming , if you meant by broken the purple buttons on the right on the border, it was fixed in Chrome. Could you please check it on Edge?

**Comment by max-programming** [comment]
Sure! I'll let you know
