### ISSUE TITLE
Publishing to Vivaldi Themes(Vivaldi 5.0 update)

### ISSUE THREAD

**Issue by im-coder-lg** [daltonmenezes/aura-theme#85]
Hi @daltonmenezes (noticed you were busy, you can see this when you are free)
I love this theme and I am using it on my Vivaldi instance. Recently(maybe not too recently, I think it was during October 25-30), Vivaldi had a new release, the 5.0 and it's a pretty big upgrade. You get a lot of new features like translation widgets in the panel, downloads, etc. But what captivated me was the [Theme Store](https://themes.vivaldi.net), where you can upload your theme to the store and anyone can download it. Matter of clicks.
So, since I use the Aura theme, can I upload the theme to the Theme Store? It's fine if you want to do it yourself, I'd recommend that. But the reason I am asking if I could release the theme there is due to the fact that you need a Vivaldi Account. Sure, you could create it, but another hitch: It makes a Webmail account. If you are not bothered by this, feel free, I'd love to help on this. If not, do tell me here, I'll try adding Aura to the Theme Store.

**Comment by im-coder-lg** [comment]
PS: I think it was November, not October.

**Comment by daltonmenezes** [comment]
Hi @im-coder-lg , thanks for letting me know, the theme has been uploaded but awaits for approval. When approved, I will update the docs and close this issue. I belive the final link on the store will be [this one](https://themes.vivaldi.net/themes/QBEJe8kvyP9).

Thanks again 💜
