### ISSUE TITLE
VS Code: Poor status bar text contrast while debugging 

### ISSUE THREAD

**Issue by matthewrayner** [daltonmenezes/aura-theme#87]
The status bar text is difficult to read when the debugger is running.

<img width="395" alt="Screen Shot 2021-12-07 at 1 12 31 PM" src="https://user-images.githubusercontent.com/30171253/144942698-01d12afb-7faa-4310-a4bf-d43c23882210.png">

**Comment by redoxeon** [comment]
I also noticed this

**Comment by daltonmenezes** [comment]
I'm working on it right now 🚀

**Comment by daltonmenezes** [comment]
@matthewrayner  @redoxeon how about this one?
![Captura de Tela 2022-02-19 às 12 57 18](https://user-images.githubusercontent.com/1149845/154808419-41e77073-5c21-407b-9099-ef2e54c27c02.png)
