### ISSUE TITLE
Implement for IntelliJ IDEA

### ISSUE THREAD

**Issue by DanielHGimenez** [daltonmenezes/aura-theme#9]
Implement the theme for IntelliJ IDEA

**Comment by bearkfear** [comment]
I use android studio, i will be veryyyyyy happy to have this theme there. PLEASSEEEEE <3

**Comment by PhyberApex** [comment]
I guess the help wanted label means you're open on a PR for this?

**Comment by trzpiot** [comment]
Hi @daltonmenezes, I can give it a try. 😃

**Comment by daltonmenezes** [comment]
@trzpiot sure, The Visual Studio Code port must be used as the guide to put the colors in a right way. Also, don't forget to read the [docs](https://github.com/daltonmenezes/aura-theme#documentation) and anticipate the knowledge about the [checklist](https://github.com/daltonmenezes/aura-theme/blob/main/.github/PULL_REQUEST_TEMPLATE.md) that PR must have. I'm going to assign you to this issue, just let me know if you need any help 💜

**Comment by jbrooksuk** [comment]
I've just used [JetBrains/colorSchemeTool](https://github.com/JetBrains/colorSchemeTool) to generate a converted version of aura-theme. You can get it here: https://gist.github.com/jbrooksuk/af4bd3a8292e713a0f45f60406acb3c1

**Comment by trzpiot** [comment]
Sorry that nothing has come so far.
@jbrooksuk, thanks! 🚀 Do you want to create the port as well or should I do it? Unfortunately I can't make any time promises, but I'll try my best.

**Comment by jbrooksuk** [comment]
@trzpiot it's not something I'm going to pursue, sorry. I'm not super familiar with the theming of IntelliJ editors. I just converted it quickly - it's definitely not perfect.

**Comment by trzpiot** [comment]
Hi @daltonmenezes,

unfortunately I won't manage to build the port in the near future, which is why I'm taking myself out as the assignee. Sorry folks.
