### ISSUE TITLE
Add new VSCode theme variant to support Operator font

### ISSUE THREAD

**Issue by aigdonia** [daltonmenezes/aura-theme#93]
I think one missing refinement to this beautiful theme is to consider the beautiful `Operator` font and fancy [Ligtures](https://github.com/kiliman/operator-mono-lig#operator-mono-ligatures).

I'd work on this my self, I'm adding this Issue to follow the readme that suggest to add issue before a PR

**Comment by daltonmenezes** [comment]
Hi @aigdonia , there are actually no fonts in any variant available, just the **Getting full experience** section recommending some things I use, but the choice is up to the user, the Aura theme itself shouldn't impute this to users. 💜
