### ISSUE TITLE
Color of the Sublime Text bracket and tag scope indicators makes them hard to see

### ISSUE THREAD

**Issue by Hendrikto** [daltonmenezes/aura-theme#96]
In issue #94, I identified the problem that bracket and tag scope indicators were not visible. This was fixed with PR #95, but the indicators now actually being visible revealed another problem: Their color (`accent17`) makes them hard to see. The contrast between the background color and `accent17` is minimal.

I am no design expert, and I am colorblind (protanoptic), so I don't think I am the right person for choosing a different color. If somebody else (maybe @daltonmenezes himself?) suggests a more suitable color (i.e. higher contrast with the background color), I would volunteer to implement that change.

**Comment by daltonmenezes** [comment]
Hi @Hendrikto , you are the perfect person to help up to build something more inclusive and for everyone. Could you please test some accents and provide us screenshots and the related accent in writing showing what accents are better for you? It'll help us to choose the best one for all of us or even we can work in a specific variant for color blinders. What do you think about it?

**Comment by Hendrikto** [comment]
`accent1` and `accent2` both work well. See https://github.com/daltonmenezes/aura-theme/pull/95#issuecomment-1024765303
